/// A selectable record-start/stop cue voice: an `id`, a display `label`, and the
/// picker `group` it belongs to. `id` doubles as the cue stem the host resolves
/// against its own bundle: `<id>-start` / `<id>-stop`. The `.none` pack plays
/// nothing.
///
/// **The engine ships no voices and no audio.** A `SoundPack` is a descriptor the
/// host supplies — Blurt's 192 vintage-synth voices are generated by
/// `scripts/generate-sounds.swift` into the app target, next to the `.m4a` cues
/// they name (`App/Blurt/Blurt/SoundPackCatalog.swift`). That split is the point:
/// a catalog whose files aren't in the same bundle resolves to silence, so the
/// list and the audio ship together or not at all. Collect them into a
/// `SoundPackCatalog` to get the picker sections, lookup, and the
/// decode-with-default rule.
public struct SoundPack: Sendable, Hashable, Identifiable {
  public let id: String
  /// The voice's name, e.g. "Orchestra" or "A11 Brass" — shown in the picker.
  public let label: String
  /// The picker section this voice belongs to, e.g. "Yamaha DX7 · ROM1A" or
  /// "Roland Juno-106 · A". nil for `.none`.
  public let group: String?

  /// Public because a host builds its own catalog: this is how voices are
  /// declared from outside the module.
  public init(id: String, label: String, group: String?) {
    self.id = id
    self.label = label
    self.group = group
  }

  /// The "no sound" choice. Not part of any catalog — `SoundPackCatalog` keeps it
  /// reachable no matter what voices it was handed, so "silence the cues" is
  /// never a choice a host's catalog can take away.
  public static let none = SoundPack(id: "none", label: "None", group: nil)

  /// True for the `.none` pack — the one voice with no cue files and no synth
  /// credit. A catalog entry always carries a `group` (its picker section), so its
  /// absence is what marks the silent pack. Internal: the app asks via
  /// `startFileName`/`stopFileName`, so exporting this would only trip
  /// periphery's redundant-public check.
  var isSilent: Bool { group == nil }

  /// Cue stem for the start cue, or nil when no sound plays.
  public var startFileName: String? { isSilent ? nil : "\(id)-start" }

  /// Cue stem for the stop cue, or nil when no sound plays.
  public var stopFileName: String? { isSilent ? nil : "\(id)-stop" }
}
